export const Pets = [
  {
    type: "Dog",
    name: "Bradley",
    adoptionStatus: "Adopted",
    picture: "",
    height: 14,
    weight: 75,
    color: "White/Blue",
    bio: "This is a bio if dog Bradley. The whole history of his life. I hope is not too short",
    hypoallergnic: false,
    dietary: [],
    breed: "Pit Bull Mix",
  },
  {
    type: "Cat",
    name: "Rajah",
    adoptionStatus: "Adopted",
    picture: "",
    height: 4,
    weight: 65,
    color: "Brown Tabby",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Cat",
    name: "Pebbles",
    adoptionStatus: "Adopted",
    picture: "",
    height: 84,
    weight: 75,
    color: "Calico",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Dog",
    name: "Johnny",
    adoptionStatus: "Adopted",
    picture: "",
    height: 66,
    weight: 88,
    color: "Blue/White",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Pit Bull",
  },
  {
    type: "Cat",
    name: "Miso",
    adoptionStatus: "Adopted",
    picture: "",
    height: 26,
    weight: 8,
    color: "Brown Tabby/White",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Cat",
    name: "Lucky Charm",
    adoptionStatus: "Adopted",
    picture: "",
    height: 10,
    weight: 69,
    color: "Orange Tabby",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Dog",
    name: "Megatron",
    adoptionStatus: "Adopted",
    picture: "",
    height: 44,
    weight: 14,
    color: "Red",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Dachshund/Chihuahua Shorthair",
  },
  {
    type: "Dog",
    name: "Moomoo",
    adoptionStatus: "Adopted",
    picture: "",
    height: 98,
    weight: 96,
    color: "White/Black",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "French Bulldog/Pit Bull",
  },
  {
    type: "Dog",
    name: "Lindi",
    adoptionStatus: "Adopted",
    picture: "",
    height: 94,
    weight: 67,
    color: "Black/White",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Pit Bull Mix",
  },
  {
    type: "Dog",
    name: "Church",
    adoptionStatus: "Adopted",
    picture: "",
    height: 97,
    weight: 17,
    color: "Brown Brindle",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Plott Hound Mix",
  },
  {
    type: "Cat",
    name: "Huncho",
    adoptionStatus: "Adopted",
    picture: "",
    height: 85,
    weight: 47,
    color: "White/Brown Tabby",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Dog",
    name: "Calvin",
    adoptionStatus: "Adopted",
    picture: "",
    height: 40,
    weight: 90,
    color: "Tan/White",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Border Terrier Mix",
  },
  {
    type: "Cat",
    name: "Sandi",
    adoptionStatus: "Adopted",
    picture: "",
    height: 52,
    weight: 39,
    color: "Torbie/White",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Other",
    name: "Bun Jovi",
    adoptionStatus: "Adopted",
    picture: "",
    height: 48,
    weight: 1,
    color: "White",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Californian",
  },
  {
    type: "Cat",
    name: "Lucy",
    adoptionStatus: "Adopted",
    picture: "",
    height: 29,
    weight: 24,
    color: "Blue Tabby/White",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Cat",
    name: "Frida",
    adoptionStatus: "Adopted",
    picture: "",
    height: 28,
    weight: 36,
    color: "White/Black",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Cat",
    name: "Ozzy",
    adoptionStatus: "Adopted",
    picture: "",
    height: 43,
    weight: 61,
    color: "Blue Tabby/White",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Domestic Medium Hair Mix",
  },
  {
    type: "Cat",
    name: "Finnegan",
    adoptionStatus: "Adopted",
    picture: "",
    height: 37,
    weight: 70,
    color: "Flame Point",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Siamese Mix",
  },
  {
    type: "Dog",
    name: "Spike",
    adoptionStatus: "Adopted",
    picture: "",
    height: 56,
    weight: 95,
    color: "Black/White",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Chihuahua Shorthair Mix",
  },
  {
    type: "Dog",
    name: "Kash",
    adoptionStatus: "Adopted",
    picture: "",
    height: 60,
    weight: 69,
    color: "Black",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Chihuahua Shorthair/Pomeranian",
  },
  {
    type: "Dog",
    name: "Cheyenne",
    adoptionStatus: "Adopted",
    picture: "",
    height: 33,
    weight: 75,
    color: "Blue/Tan",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Dachshund Wirehair/Miniature Poodle",
  },
  {
    type: "Cat",
    name: "Jorge Mcfly",
    adoptionStatus: "Adopted",
    picture: "",
    height: 61,
    weight: 100,
    color: "Black/White",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Dog",
    name: "Sassy",
    adoptionStatus: "Adopted",
    picture: "",
    height: 44,
    weight: 29,
    color: "White/Brown",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Cairn Terrier Mix",
  },
  {
    type: "Cat",
    name: "Gretchen",
    adoptionStatus: "Adopted",
    picture: "",
    height: 43,
    weight: 14,
    color: "Tortie",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Dog",
    name: "Theo",
    adoptionStatus: "Adopted",
    picture: "",
    height: 90,
    weight: 68,
    color: "Tan/Black",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Swedish Vallhund Mix",
  },
  {
    type: "Dog",
    name: "Bessie",
    adoptionStatus: "Adopted",
    picture: "",
    height: 57,
    weight: 72,
    color: "White/Brown",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Australian Cattle Dog Mix",
  },
  {
    type: "Cat",
    name: "Fern",
    adoptionStatus: "Adopted",
    picture: "",
    height: 21,
    weight: 87,
    color: "Blue Tabby/White",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Dog",
    name: "Merlin",
    adoptionStatus: "Adopted",
    picture: "",
    height: 65,
    weight: 3,
    color: "Blue/White",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Pit Bull Mix",
  },
  {
    type: "Dog",
    name: "Shadow",
    adoptionStatus: "Adopted",
    picture: "",
    height: 53,
    weight: 13,
    color: "Black",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Flat Coat Retriever Mix",
  },
  {
    type: "Cat",
    name: "Elsa",
    adoptionStatus: "Adopted",
    picture: "",
    height: 68,
    weight: 32,
    color: "Brown Tabby",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Dog",
    name: "River",
    adoptionStatus: "Adopted",
    picture: "",
    height: 77,
    weight: 79,
    color: "Tan/White",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Labrador Retriever Mix",
  },
  {
    type: "Dog",
    name: "Pippi",
    adoptionStatus: "Adopted",
    picture: "",
    height: 40,
    weight: 9,
    color: "Brown/White",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Chihuahua Shorthair Mix",
  },
  {
    type: "Dog",
    name: "Max",
    adoptionStatus: "Adopted",
    picture: "",
    height: 10,
    weight: 62,
    color: "Sable",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "German Shepherd Mix",
  },
  {
    type: "Dog",
    name: "Bailey",
    adoptionStatus: "Adopted",
    picture: "",
    height: 58,
    weight: 29,
    color: "White/Brown",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Pit Bull/Labrador Retriever",
  },
  {
    type: "Cat",
    name: "Chester",
    adoptionStatus: "Adopted",
    picture: "",
    height: 92,
    weight: 44,
    color: "Black Tabby",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Dog",
    name: "Dolly",
    adoptionStatus: "Adopted",
    picture: "",
    height: 96,
    weight: 23,
    color: "Tan/White",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Beagle Mix",
  },
  {
    type: "Cat",
    name: "Oliver",
    adoptionStatus: "Adopted",
    picture: "",
    height: 50,
    weight: 15,
    color: "Orange Tabby",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Dog",
    name: "Ryker",
    adoptionStatus: "Adopted",
    picture: "",
    height: 68,
    weight: 70,
    color: "Brown/White",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Pit Bull Mix",
  },
  {
    type: "Dog",
    name: "Rosie",
    adoptionStatus: "Adopted",
    picture: "",
    height: 57,
    weight: 59,
    color: "Blue",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Pit Bull Mix",
  },
  {
    type: "Cat",
    name: "Fern",
    adoptionStatus: "Adopted",
    picture: "",
    height: 49,
    weight: 63,
    color: "Calico",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Domestic Shorthair",
  },
  {
    type: "Dog",
    name: "Ivy",
    adoptionStatus: "Adopted",
    picture: "",
    height: 64,
    weight: 7,
    color: "Blue",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Blue Lacy/Australian Kelpie",
  },
  {
    type: "Dog",
    name: "Olive",
    adoptionStatus: "Adopted",
    picture: "",
    height: 74,
    weight: 2,
    color: "Brown Brindle",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Mastiff Mix",
  },
  {
    type: "Dog",
    name: "Molly",
    adoptionStatus: "Adopted",
    picture: "",
    height: 48,
    weight: 17,
    color: "White",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Yorkshire Terrier/Chihuahua Shorthair",
  },
  {
    type: "Dog",
    name: "Promise",
    adoptionStatus: "Adopted",
    picture: "",
    height: 70,
    weight: 6,
    color: "Yellow",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Labrador Retriever Mix",
  },
  {
    type: "Dog",
    name: "Lucy",
    adoptionStatus: "Adopted",
    picture: "",
    height: 48,
    weight: 3,
    color: "White",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Maltese Mix",
  },
  {
    type: "Cat",
    name: "Cinnamon",
    adoptionStatus: "Adopted",
    picture: "",
    height: 67,
    weight: 32,
    color: "Brown Tabby",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Dog",
    name: "Lily",
    adoptionStatus: "Adopted",
    picture: "",
    height: 84,
    weight: 76,
    color: "Black/White",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Border Collie/Labrador Retriever",
  },
  {
    type: "Dog",
    name: "Ripley",
    adoptionStatus: "Adopted",
    picture: "",
    height: 10,
    weight: 92,
    color: "Tan/White",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Labrador Retriever Mix",
  },
  {
    type: "Dog",
    name: "Lobo",
    adoptionStatus: "Adopted",
    picture: "",
    height: 72,
    weight: 34,
    color: "Black/Tricolor",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Australian Shepherd Mix",
  },
  {
    type: "Dog",
    name: "Jaqueline",
    adoptionStatus: "Adopted",
    picture: "",
    height: 68,
    weight: 54,
    color: "Red",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Staffordshire Mix",
  },
  {
    type: "Cat",
    name: "Marvin",
    adoptionStatus: "Adopted",
    picture: "",
    height: 48,
    weight: 91,
    color: "Brown Tabby",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Dog",
    name: "Sheldon",
    adoptionStatus: "Adopted",
    picture: "",
    height: 19,
    weight: 22,
    color: "Tricolor",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Cardigan Welsh Corgi Mix",
  },
  {
    type: "Dog",
    name: "Kane",
    adoptionStatus: "Adopted",
    picture: "",
    height: 30,
    weight: 82,
    color: "Black/White",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Labrador Retriever/Pit Bull",
  },
  {
    type: "Cat",
    name: "Kitten",
    adoptionStatus: "Adopted",
    picture: "",
    height: 90,
    weight: 10,
    color: "Brown Tabby",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Cat",
    name: "Liam",
    adoptionStatus: "Adopted",
    picture: "",
    height: 51,
    weight: 24,
    color: "Blue/White",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Domestic Longhair Mix",
  },
  {
    type: "Dog",
    name: "Alfie",
    adoptionStatus: "Adopted",
    picture: "",
    height: 68,
    weight: 64,
    color: "Cream/Gray",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Soft Coated Wheaten Terrier Mix",
  },
  {
    type: "Dog",
    name: "Shades",
    adoptionStatus: "Adopted",
    picture: "",
    height: 10,
    weight: 66,
    color: "Black/White",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Labrador Retriever Mix",
  },
  {
    type: "Dog",
    name: "Penny",
    adoptionStatus: "Adopted",
    picture: "",
    height: 76,
    weight: 71,
    color: "Buff",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Chihuahua Shorthair Mix",
  },
  {
    type: "Dog",
    name: "Ginger",
    adoptionStatus: "Adopted",
    picture: "",
    height: 32,
    weight: 36,
    color: "Red/White",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Chihuahua Shorthair Mix",
  },
  {
    type: "Dog",
    name: "Lolly",
    adoptionStatus: "Adopted",
    picture: "",
    height: 42,
    weight: 57,
    color: "Brown Brindle",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Labrador Retriever Mix",
  },
  {
    type: "Dog",
    name: "Sheila",
    adoptionStatus: "Adopted",
    picture: "",
    height: 94,
    weight: 8,
    color: "Brown/Black",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "German Shepherd Mix",
  },
  {
    type: "Dog",
    name: "Rocket",
    adoptionStatus: "Adopted",
    picture: "",
    height: 20,
    weight: 75,
    color: "Tricolor",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Chihuahua Shorthair Mix",
  },
  {
    type: "Dog",
    name: "Tucker",
    adoptionStatus: "Adopted",
    picture: "",
    height: 51,
    weight: 32,
    color: "Brown/White",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Labrador Retriever Mix",
  },
  {
    type: "Cat",
    name: "Sugar",
    adoptionStatus: "Adopted",
    picture: "",
    height: 53,
    weight: 63,
    color: "Black",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Dog",
    name: "Chula",
    adoptionStatus: "Adopted",
    picture: "",
    height: 24,
    weight: 45,
    color: "Tan",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Chihuahua Shorthair/Dachshund",
  },
  {
    type: "Other",
    name: "Colossus",
    adoptionStatus: "Adopted",
    picture: "",
    height: 81,
    weight: 4,
    color: "Gray",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Chinchilla-Stnd Mix",
  },
  {
    type: "Dog",
    name: "Aria",
    adoptionStatus: "Adopted",
    picture: "",
    height: 89,
    weight: 51,
    color: "White/Black",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Cardigan Welsh Corgi/English Setter",
  },
  {
    type: "Cat",
    name: "Captamerica",
    adoptionStatus: "Adopted",
    picture: "",
    height: 72,
    weight: 10,
    color: "Blue/White",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Dog",
    name: "Oreo",
    adoptionStatus: "Adopted",
    picture: "",
    height: 55,
    weight: 23,
    color: "Black/White",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Border Collie Mix",
  },
  {
    type: "Cat",
    name: "Bacon",
    adoptionStatus: "Adopted",
    picture: "",
    height: 30,
    weight: 87,
    color: "Blue",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Cat",
    name: "Winnie",
    adoptionStatus: "Adopted",
    picture: "",
    height: 90,
    weight: 28,
    color: "Blue",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Russian Blue Mix",
  },
  {
    type: "Cat",
    name: "Smoke",
    adoptionStatus: "Adopted",
    picture: "",
    height: 31,
    weight: 84,
    color: "Blue",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Russian Blue Mix",
  },
  {
    type: "Cat",
    name: "Pepper",
    adoptionStatus: "Adopted",
    picture: "",
    height: 26,
    weight: 5,
    color: "Black/White",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Cat",
    name: "Mittens",
    adoptionStatus: "Adopted",
    picture: "",
    height: 53,
    weight: 50,
    color: "Brown Tabby/White",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Cat",
    name: "Luke",
    adoptionStatus: "Adopted",
    picture: "",
    height: 52,
    weight: 39,
    color: "Black/White",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Cat",
    name: "Shazie",
    adoptionStatus: "Adopted",
    picture: "",
    height: 52,
    weight: 70,
    color: "Black Tabby",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Domestic Medium Hair Mix",
  },
  {
    type: "Dog",
    name: "Kyra",
    adoptionStatus: "Adopted",
    picture: "",
    height: 54,
    weight: 1,
    color: "Fawn/White",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Pit Bull Mix",
  },
  {
    type: "Cat",
    name: "Moe",
    adoptionStatus: "Adopted",
    picture: "",
    height: 40,
    weight: 22,
    color: "Brown Tabby/White",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Dog",
    name: "Daisy",
    adoptionStatus: "Adopted",
    picture: "",
    height: 10,
    weight: 78,
    color: "Tan/White",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Chihuahua Shorthair Mix",
  },
  {
    type: "Cat",
    name: "Max",
    adoptionStatus: "Adopted",
    picture: "",
    height: 90,
    weight: 23,
    color: "Brown Tabby",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Dog",
    name: "Brody",
    adoptionStatus: "Adopted",
    picture: "",
    height: 40,
    weight: 12,
    color: "White/Brown Brindle",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Parson Russell Terrier Mix",
  },
  {
    type: "Dog",
    name: "Lucky",
    adoptionStatus: "Adopted",
    picture: "",
    height: 93,
    weight: 31,
    color: "White",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Miniature Poodle Mix",
  },
  {
    type: "Dog",
    name: "Bear",
    adoptionStatus: "Adopted",
    picture: "",
    height: 12,
    weight: 18,
    color: "Black",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Flat Coat Retriever Mix",
  },
  {
    type: "Dog",
    name: "Quill",
    adoptionStatus: "Adopted",
    picture: "",
    height: 12,
    weight: 56,
    color: "White/Black",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Labrador Retriever Mix",
  },
  {
    type: "Cat",
    name: "Pumpkin",
    adoptionStatus: "Fostered",
    picture: "",
    height: 52,
    weight: 95,
    color: "Orange Tabby",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Domestic Medium Hair Mix",
  },
  {
    type: "Dog",
    name: "Luke",
    adoptionStatus: "Fostered",
    picture: "",
    height: 17,
    weight: 77,
    color: "Tan/Black",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Labrador Retriever/Beagle",
  },
  {
    type: "Dog",
    name: "Ittybitty",
    adoptionStatus: "Fostered",
    picture: "",
    height: 74,
    weight: 71,
    color: "Black/White",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Pit Bull Mix",
  },
  {
    type: "Dog",
    name: "Benji",
    adoptionStatus: "Fostered",
    picture: "",
    height: 17,
    weight: 43,
    color: "Tan",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Border Terrier Mix",
  },
  {
    type: "Dog",
    name: "Rose",
    adoptionStatus: "Fostered",
    picture: "",
    height: 67,
    weight: 24,
    color: "Yellow",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Labrador Retriever/Jack Russell Terrier",
  },
  {
    type: "Cat",
    name: "Shakti",
    adoptionStatus: "Fostered",
    picture: "",
    height: 41,
    weight: 21,
    color: "Blue/White",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Cat",
    name: "Toots",
    adoptionStatus: "Fostered",
    picture: "",
    height: 56,
    weight: 55,
    color: "Blue Tabby",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Dog",
    name: "Boone",
    adoptionStatus: "Fostered",
    picture: "",
    height: 10,
    weight: 63,
    color: "Liver/White",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "English Springer Spaniel Mix",
  },
  {
    type: "Dog",
    name: "Ruby",
    adoptionStatus: "Fostered",
    picture: "",
    height: 62,
    weight: 72,
    color: "Brown Brindle",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Catahoula/Labrador Retriever",
  },
  {
    type: "Dog",
    name: "White Boy",
    adoptionStatus: "Fostered",
    picture: "",
    height: 31,
    weight: 24,
    color: "White/Black",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Pit Bull Mix",
  },
  {
    type: "Dog",
    name: "Gio",
    adoptionStatus: "Fostered",
    picture: "",
    height: 80,
    weight: 86,
    color: "Red/Tan",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Chihuahua Shorthair Mix",
  },
  {
    type: "Cat",
    name: "Jolie",
    adoptionStatus: "Fostered",
    picture: "",
    height: 30,
    weight: 40,
    color: "Brown Tabby/White",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Dog",
    name: "Yoshi",
    adoptionStatus: "Fostered",
    picture: "",
    height: 73,
    weight: 75,
    color: "Blue/White",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Pit Bull Mix",
  },
  {
    type: "Dog",
    name: "Toby",
    adoptionStatus: "Fostered",
    picture: "",
    height: 20,
    weight: 28,
    color: "Cream",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Chihuahua Longhair Mix",
  },
  {
    type: "Dog",
    name: "Charlie",
    adoptionStatus: "Fostered",
    picture: "",
    height: 10,
    weight: 89,
    color: "White/Brown",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Treeing Walker Coonhound Mix",
  },
  {
    type: "Cat",
    name: "Stella Luna",
    adoptionStatus: "Fostered",
    picture: "",
    height: 45,
    weight: 77,
    color: "Black/White",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Domestic Medium Hair Mix",
  },
  {
    type: "Dog",
    name: "Luna",
    adoptionStatus: "Fostered",
    picture: "",
    height: 46,
    weight: 8,
    color: "Black/White",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Siberian Husky Mix",
  },
  {
    type: "Cat",
    name: "Lucy",
    adoptionStatus: "Fostered",
    picture: "",
    height: 39,
    weight: 30,
    color: "Tortie",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Dog",
    name: "Nala",
    adoptionStatus: "Fostered",
    picture: "",
    height: 38,
    weight: 4,
    color: "Black/White",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Cocker Spaniel Mix",
  },
  {
    type: "Dog",
    name: "Preciosa",
    adoptionStatus: "Fostered",
    picture: "",
    height: 100,
    weight: 0,
    color: "Black/Tan",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Chihuahua Shorthair Mix",
  },
  {
    type: "Dog",
    name: "Sandy",
    adoptionStatus: "Fostered",
    picture: "",
    height: 19,
    weight: 93,
    color: "White",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Miniature Schnauzer/Miniature Poodle",
  },
  {
    type: "Dog",
    name: "Shy",
    adoptionStatus: "Fostered",
    picture: "",
    height: 23,
    weight: 59,
    color: "Black",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Labrador Retriever Mix",
  },
  {
    type: "Dog",
    name: "Luna",
    adoptionStatus: "Fostered",
    picture: "",
    height: 66,
    weight: 42,
    color: "Brown/White",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Labrador Retriever Mix",
  },
  {
    type: "Dog",
    name: "Georgo",
    adoptionStatus: "Fostered",
    picture: "",
    height: 49,
    weight: 35,
    color: "Chocolate/Tan",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Labrador Retriever Mix",
  },
  {
    type: "Dog",
    name: "Chucho",
    adoptionStatus: "Fostered",
    picture: "",
    height: 19,
    weight: 2,
    color: "Tan/White",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Chihuahua Shorthair Mix",
  },
  {
    type: "Cat",
    name: "Smooches",
    adoptionStatus: "Fostered",
    picture: "",
    height: 56,
    weight: 88,
    color: "Black/White",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Dog",
    name: "Shadow",
    adoptionStatus: "Fostered",
    picture: "",
    height: 54,
    weight: 83,
    color: "Black",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "German Shepherd",
  },
  {
    type: "Dog",
    name: "Sargento",
    adoptionStatus: "Fostered",
    picture: "",
    height: 19,
    weight: 42,
    color: "Red/White",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Rhod Ridgeback Mix",
  },
  {
    type: "Cat",
    name: "Mia",
    adoptionStatus: "Fostered",
    picture: "",
    height: 85,
    weight: 80,
    color: "Tortie Point",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Siamese Mix",
  },
  {
    type: "Dog",
    name: "Rosco",
    adoptionStatus: "Fostered",
    picture: "",
    height: 97,
    weight: 99,
    color: "Red/White",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Chihuahua Shorthair Mix",
  },
  {
    type: "Dog",
    name: "Canela",
    adoptionStatus: "Fostered",
    picture: "",
    height: 77,
    weight: 85,
    color: "White/Tan",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Chihuahua Shorthair",
  },
  {
    type: "Cat",
    name: "Harlem",
    adoptionStatus: "Fostered",
    picture: "",
    height: 14,
    weight: 18,
    color: "Orange Tabby",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Cat",
    name: "Miss Rose",
    adoptionStatus: "Fostered",
    picture: "",
    height: 70,
    weight: 72,
    color: "Calico",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Cat",
    name: "Loki",
    adoptionStatus: "Fostered",
    picture: "",
    height: 31,
    weight: 6,
    color: "Brown Tabby",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Domestic Longhair Mix",
  },
  {
    type: "Dog",
    name: "Malo",
    adoptionStatus: "Fostered",
    picture: "",
    height: 76,
    weight: 26,
    color: "Black",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Labrador Retriever Mix",
  },
  {
    type: "Dog",
    name: "Chaco",
    adoptionStatus: "Fostered",
    picture: "",
    height: 27,
    weight: 95,
    color: "Black/White",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Labrador Retriever Mix",
  },
  {
    type: "Dog",
    name: "Scooby",
    adoptionStatus: "Fostered",
    picture: "",
    height: 26,
    weight: 78,
    color: "Tan/Black",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "German Shepherd Mix",
  },
  {
    type: "Dog",
    name: "Lex",
    adoptionStatus: "Fostered",
    picture: "",
    height: 15,
    weight: 86,
    color: "Brown",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Boxer Mix",
  },
  {
    type: "Cat",
    name: "Peeta",
    adoptionStatus: "Fostered",
    picture: "",
    height: 69,
    weight: 28,
    color: "Orange Tabby",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Cat",
    name: "Max",
    adoptionStatus: "Fostered",
    picture: "",
    height: 64,
    weight: 91,
    color: "Orange Tabby",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Dog",
    name: "Coco",
    adoptionStatus: "Fostered",
    picture: "",
    height: 39,
    weight: 22,
    color: "White/Brown",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Pit Bull Mix",
  },
  {
    type: "Cat",
    name: "Fafali",
    adoptionStatus: "Fostered",
    picture: "",
    height: 13,
    weight: 98,
    color: "Tortie",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Dog",
    name: "Happy Camper",
    adoptionStatus: "Available",
    picture: "",
    height: 40,
    weight: 40,
    color: "Black",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Labrador Retriever Mix",
  },
  {
    type: "Dog",
    name: "Lucy",
    adoptionStatus: "Available",
    picture: "",
    height: 61,
    weight: 53,
    color: "White/Brown",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Beagle Mix",
  },
  {
    type: "Dog",
    name: "Monday",
    adoptionStatus: "Available",
    picture: "",
    height: 16,
    weight: 79,
    color: "White",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Miniature Schnauzer Mix",
  },
  {
    type: "Dog",
    name: "Edgar",
    adoptionStatus: "Available",
    picture: "",
    height: 68,
    weight: 86,
    color: "Brown/White",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Leonberger Mix",
  },
  {
    type: "Dog",
    name: "Ella",
    adoptionStatus: "Available",
    picture: "",
    height: 51,
    weight: 48,
    color: "Brown",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Chihuahua Shorthair Mix",
  },
  {
    type: "Dog",
    name: "Arnie",
    adoptionStatus: "Available",
    picture: "",
    height: 10,
    weight: 2,
    color: "Tan",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Norfolk Terrier Mix",
  },
  {
    type: "Cat",
    name: "James",
    adoptionStatus: "Available",
    picture: "",
    height: 83,
    weight: 29,
    color: "Blue Tabby",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Dog",
    name: "Valentino",
    adoptionStatus: "Available",
    picture: "",
    height: 45,
    weight: 97,
    color: "Black/Tan",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Pug/Border Terrier",
  },
  {
    type: "Dog",
    name: "Fancy",
    adoptionStatus: "Available",
    picture: "",
    height: 14,
    weight: 79,
    color: "Black/White",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Papillon/Border Collie",
  },
  {
    type: "Dog",
    name: "Novah",
    adoptionStatus: "Available",
    picture: "",
    height: 16,
    weight: 39,
    color: "White",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Pit Bull Mix",
  },
  {
    type: "Dog",
    name: "Pepper",
    adoptionStatus: "Available",
    picture: "",
    height: 10,
    weight: 21,
    color: "Black/Tricolor",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Soft Coated Wheaten Terrier Mix",
  },
  {
    type: "Dog",
    name: "Pepper",
    adoptionStatus: "Available",
    picture: "",
    height: 36,
    weight: 53,
    color: "Black/Tricolor",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Soft Coated Wheaten Terrier Mix",
  },
  {
    type: "Dog",
    name: "Truman",
    adoptionStatus: "Available",
    picture: "",
    height: 83,
    weight: 36,
    color: "White/Black",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Rat Terrier Mix",
  },
  {
    type: "Dog",
    name: "Martie",
    adoptionStatus: "Available",
    picture: "",
    height: 34,
    weight: 27,
    color: "Tricolor",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Chihuahua Shorthair Mix",
  },
  {
    type: "Dog",
    name: "Newt",
    adoptionStatus: "Available",
    picture: "",
    height: 19,
    weight: 52,
    color: "Brown Brindle/White",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Pit Bull Mix",
  },
  {
    type: "Dog",
    name: "Patrick",
    adoptionStatus: "Available",
    picture: "",
    height: 69,
    weight: 14,
    color: "Brown/Black",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Pomeranian Mix",
  },
  {
    type: "Cat",
    name: "Davis",
    adoptionStatus: "Available",
    picture: "",
    height: 94,
    weight: 83,
    color: "Brown Tabby",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Cat",
    name: "Preston",
    adoptionStatus: "Available",
    picture: "",
    height: 48,
    weight: 16,
    color: "Black/White",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Domestic Medium Hair Mix",
  },
  {
    type: "Cat",
    name: "Montgomery",
    adoptionStatus: "Available",
    picture: "",
    height: 54,
    weight: 43,
    color: "Brown Tabby/White",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Dog",
    name: "Ollie",
    adoptionStatus: "Available",
    picture: "",
    height: 82,
    weight: 52,
    color: "Black",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Australian Cattle Dog/Labrador Retriever",
  },
  {
    type: "Dog",
    name: "Meryl",
    adoptionStatus: "Available",
    picture: "",
    height: 66,
    weight: 31,
    color: "Brown Brindle/White",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Pit Bull Mix",
  },
  {
    type: "Dog",
    name: "Minnie",
    adoptionStatus: "Available",
    picture: "",
    height: 15,
    weight: 8,
    color: "Blue/Tan",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Chihuahua Shorthair Mix",
  },
  {
    type: "Cat",
    name: "Bumble",
    adoptionStatus: "Available",
    picture: "",
    height: 59,
    weight: 74,
    color: "Seal Point",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Siamese",
  },
  {
    type: "Dog",
    name: "Vinnie",
    adoptionStatus: "Available",
    picture: "",
    height: 41,
    weight: 99,
    color: "Tan/White",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Pit Bull Mix",
  },
  {
    type: "Cat",
    name: "Jasmine",
    adoptionStatus: "Available",
    picture: "",
    height: 66,
    weight: 22,
    color: "Orange Tabby/White",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Cat",
    name: "Willow",
    adoptionStatus: "Available",
    picture: "",
    height: 43,
    weight: 61,
    color: "Black",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Domestic Longhair Mix",
  },
  {
    type: "Dog",
    name: "Brie",
    adoptionStatus: "Available",
    picture: "",
    height: 50,
    weight: 42,
    color: "Brown Brindle/White",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Greyhound Mix",
  },
  {
    type: "Cat",
    name: "Lana",
    adoptionStatus: "Available",
    picture: "",
    height: 47,
    weight: 60,
    color: "White/Brown Tabby",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Cat",
    name: "Glenn",
    adoptionStatus: "Available",
    picture: "",
    height: 98,
    weight: 14,
    color: "Blue Tabby/White",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Dog",
    name: "Josh",
    adoptionStatus: "Available",
    picture: "",
    height: 46,
    weight: 41,
    color: "Black/White",
    bio: "",
    hypoallergnic: false,
    dietary: [],
    breed: "Miniature Pinscher Mix",
  },
  {
    type: "Cat",
    name: "Oreo",
    adoptionStatus: "Available",
    picture: "",
    height: 32,
    weight: 39,
    color: "Lynx Point",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Domestic Medium Hair",
  },
  {
    type: "Dog",
    name: "Delilah",
    adoptionStatus: "Available",
    picture: "",
    height: 77,
    weight: 36,
    color: "Brown Merle/White",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Pit Bull Mix",
  },
  {
    type: "Cat",
    name: "Snowflake",
    adoptionStatus: "Available",
    picture: "",
    height: 30,
    weight: 63,
    color: "Cream Tabby/White",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Cat",
    name: "Dora",
    adoptionStatus: "Available",
    picture: "",
    height: 23,
    weight: 54,
    color: "Calico",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    type: "Cat",
    name: "Cosmo",
    adoptionStatus: "Available",
    picture: "",
    height: 24,
    weight: 9,
    color: "Chocolate",
    bio: "",
    hypoallergnic: true,
    dietary: [],
    breed: "Domestic Shorthair Mix",
  },
];
